### ISSUE TITLE
Android Implementation

### ISSUE THREAD

**Issue by danielgek** [EddyVerbruggen/nativescript-secure-storage#1]
Hi @EddyVerbruggen, are you planing to implement the android side?

I do have an implementation of your nativescript-touchid plugin for android, i haven't made a PR because the plugin name suggests it only cares about ios(touchid),

I think, it would be cool to have a plugin for security that would handle fingerprint auth and secure storage and things related to security in one plugin, i have actually started to work on this idea and published a plugin with this objective [nativescript-security](https://github.com/NMA-SPMS/nativescript-security), right after publishing the plugin i came across this repository, that is actually the next feature that i want to implement, what do you think about this?

**Comment by EddyVerbruggen** [comment]
Hi!

Android is definitely planned!

I'm not a fan of mixing storage and fingerprint api's in one plugin. I'd rather have focussed plugins with a clear purpose, API, doc and tests. I've seen monolithic plugins in the past that buried themselves in maintenance work.

I would love to see a PR on the touchid plugin to support android as well of course!

Leaving this open for the Android impl of this plugin.

Thanks,
Eddy

**Comment by EddyVerbruggen** [comment]
Android support has just been released with 2.0.0

**Comment by danielgek** [comment]
thanks i will make a pull request for de touchid plugin with the android implementation
