### ISSUE TITLE
Questions regarding encryption

### ISSUE THREAD

**Issue by VChabrette** [EddyVerbruggen/nativescript-secure-storage#14]
Hi @EddyVerbruggen ! Firstly, thanks a lot for all the work you put in this plugin.

However I have two (maybe foolish) questions, because I'm currently working for a client who has important needs regarding security : 
- Is there any encryption on the stored data by default ? By looking at Hawk documentation (I'm working on an Android-only app) it seems like there is AES by default, but I'm not really sure about that
- Do you plan to add the ability to specify an encryption while initializing the SecureStorage ?

Thanks in advance for your response and for any additional info you might have on the stored data security :smile:

**Comment by EddyVerbruggen** [comment]
Hi, I'm not planning adding things, so that answers the second question. Regarding the first one, I don't think Hawk is the definitive answer to secure storage on Android, but at the time I needed this I couldn't find a better solution. Open to ideas as always though.

Cheers,
Eddy
