### ISSUE TITLE
Data stored in ios with secure storage persist even if I remove the app

### ISSUE THREAD

**Issue by shrutisinghal** [EddyVerbruggen/nativescript-secure-storage#17]
Hi,

I saved some data in ios app with secure storage. Deleted the app from the device. Re installed the app and somehow I am still able to access the previously stored data through secure storage. It should not, right?

**Comment by EddyVerbruggen** [comment]
It seems to depend on the iOS version. [Google it](https://www.google.com/search?q=ios+keychain+data+persist+after+removing+app&oq=ios+keychain+data+persist+after+removing+app&aqs=chrome..69i57.10640j0j7&sourceid=chrome&ie=UTF-8).

**Comment by shrutisinghal** [comment]
@EddyVerbruggen Oh great! Thanks!
