### ISSUE TITLE
Is there a way to get an array of all stored keys?

### ISSUE THREAD

**Issue by trashbytes** [EddyVerbruggen/nativescript-secure-storage#18]
I'd love to do some cleanup of obsolete data and to iterate and check through them I would need to know which keys are stored.
Is that possible?

**Comment by EddyVerbruggen** [comment]
No, you have to do that housekeeping yourself.. there is native call I could use to give all those values. So keep a list of keys in your code, or throw everything in a JSON object and store that, so you can wipe the object.

**Comment by trashbytes** [comment]
Thank you, sir!
