### ISSUE TITLE
Increase the security for when the keys are accessible on iOS

### ISSUE THREAD

**Issue by PeterStaev** [EddyVerbruggen/nativescript-secure-storage#19]
From what I see from the code you use the default `kSecAttrAccessibleAlwaysThisDeviceOnly`. This is really not that secure since the data could be accessed even if the phone is restarted and/or locked. I think it is best to use `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`. Or may be provide a way to customize the setting?

**Comment by SonofNun15** [comment]
Any thoughts on how to apply this more secure `kSecAttrAccessibleWhenUnlockedThisDeviceOnly` for iOS devices only without breaking apps that also run on Android?

**Comment by PeterStaev** [comment]
@SonofNun15 , that's easy. When you initialize the `SecureStorage` you check and you send the parameter only if iOS. Something like this:
```ts
const ss = new SecureStorage(isIOS ? kSecAttrAccessibleWhenUnlockedThisDeviceOnly : undefined)
```

**Comment by SonofNun15** [comment]
Thanks! I didn't know `isIOS` was a thing, still pretty new to NativeScript development. Appreciate the insight!
