### ISSUE TITLE
Async Operations?

### ISSUE THREAD

**Issue by tomfaltesek** [EddyVerbruggen/nativescript-secure-storage#29]
Hi Eddy. Thanks for your hard work on this plugin.

I took a quick peek at the source to see how we're handling sync vs. async operations and I couldn't actually find any real async operations. It looks like the async APIs simply do the exact same thing as the sync operations, but they're wrapped in a promise.

Is there any reason for a consumer of this plugin to leverage the async methods over the sync methods? Let me know if I'm mistaken here.

**Comment by EddyVerbruggen** [comment]
If you want to have your code execution halted during usage of this plugin, you can use the sync version. Nothing special, just that.

**Comment by tomfaltesek** [comment]
Yes -- Fair enough. I guess I expected there to be async options for Hawk and Conceal. Overthinking it, I suppose.

Thanks for your reply.
