### ISSUE TITLE
iOS Default Keychain Access is Deprecated

### ISSUE THREAD

**Issue by ScottAtRedHawk** [EddyVerbruggen/nativescript-secure-storage#32]
Hi @EddyVerbruggen ,
I just wanted to let you know that in the readme is says the default iOS keychain access is kSecAttrAccessibleAlwaysThisDeviceOnly, which is deprecated (https://developer.apple.com/documentation/security/ksecattraccessiblealwaysthisdeviceonly). I think a better default might be kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly (https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlockthisdeviceonly).

Thanks for the work you put into these plugins!

**Comment by EddyVerbruggen** [comment]
Looks like you're right, thanks for the heads-up! I'll release a new version in a minute.

**Comment by ScottAtRedHawk** [comment]
@EddyVerbruggen You may want to update this section of the README.md https://github.com/EddyVerbruggen/nativescript-secure-storage/blob/master/README.md#ios-security with regards to this issue. Thanks!

**Comment by EddyVerbruggen** [comment]
Yeah you're right.. want to send a PR?
