### ISSUE TITLE
First run should not be assigned on constructor 

### ISSUE THREAD

**Issue by kefahB** [EddyVerbruggen/nativescript-secure-storage#35]
Hi @EddyVerbruggen, 
I remark an issue on the concept to do stuff with "First run", you declare this on constructor : 

```ts
  constructor() {
    this.isFirst = applicationSettings.getBoolean(SecureStorageCommon.IS_FIRST_RUN, true);
    if (this.isFirst) {
      applicationSettings.setBoolean(SecureStorageCommon.IS_FIRST_RUN, false);
    }
  }
```
Since this is declared on constructor we can not do some think with the first run because you set immediately the `SecureStorageCommon.IS_FIRST_RUN` to false, if I call the `isFirstRun()` or `clearAllOnFirstRun()` or `clearAllOnFirstRunSync()` will return always `false` cause t
it is already set on the constructor.

Maybe change refactor the tow method `isFirstRunSync` and `isFirstRunSync` and delete [those lines](https://github.com/EddyVerbruggen/nativescript-secure-storage/blob/c0068eb75e89647daf6713c049cf383dd54b80d8/src/secure-storage.common.ts#L29-L31) from constructor : 
```ts
public isFirstRunSync(): boolean {
     if (this.isFirst) {
          applicationSettings.setBoolean(SecureStorageCommon.IS_FIRST_RUN, false);
          return true;
    }
  
   return false;
}

public isFirstRun(): Promise<boolean> {
    return new Promise<boolean>((resolve, reject) => {
         if (this.isFirst) {
            applicationSettings.setBoolean(SecureStorageCommon.IS_FIRST_RUN, false);
            resolve(true);
         }
        resolve(false);
    });
}
```

**Comment by EddyVerbruggen** [comment]
@kefahB Actually, the value is cached in `this.isFirst` (second line in your first snippet). So as long as *that instance is reused* [this line](https://github.com/EddyVerbruggen/nativescript-secure-storage/blob/c0068eb75e89647daf6713c049cf383dd54b80d8/src/secure-storage.common.ts#L51) will return that initially cached value.

**Comment by kefahB** [comment]
@EddyVerbruggen,
Yes of course, but the I think is that the issu in it, is cached to `false` before that we can use the functions `isFirstRun` or `isFirstRunSync`.

Maybe I am not clean how explain, I give an exemple :

index.ts
```ts
// Here first run is TRUE
const secure = new SecureStorage();

// Now first run is FALSE

secure.isFirstRun.then(res => {
  
    console.log(res); // It always will be false because is cached to false on constructor

    if(res) {
        // Do some stuff....
    }

});
```

If I have to do some stuff when the value is true I can not because it will never be `true` after caller `new SecureStorage()`

**Comment by EddyVerbruggen** [comment]
@kefahB If that cached value is `false` then there's a bug because it's supposed to be `true` on first run and `secure.isFirstRun` should return that value.

Do you see this issue on both platforms?

**Comment by kefahB** [comment]
No just on IOS cause.

I will do some extra testing and tell you .. I know you have a lot to do 😉
