### ISSUE TITLE
Biometrically authenticate user when he tries to read a key on Android

### ISSUE THREAD

**Issue by bliulin** [EddyVerbruggen/nativescript-secure-storage#37]
Hi @EddyVerbruggen ,

From what I see in the documentation and code the feature of requiring the user to authenticate with his fingerprint/face in order to read/write a key in the key store is only available on iOS? Will it be available on Android in the future? Thanks!

```
// iOS
export class SecureStorage { ...
constructor(accessibilityType: string = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly) { ... }

// Android
export class SecureStorage { ...
// parameterless ctor... no way to provide accessibility type
constructor() { ... }
```

**Comment by EddyVerbruggen** [comment]
It's not planned for Android.
