### ISSUE TITLE
Crash on SecureStorage.prototype.removeAll

### ISSUE THREAD

**Issue by TheGothian** [EddyVerbruggen/nativescript-secure-storage#42]
Seams that SAMKeychain.allAccounts(); can return nil
This will result in for (var i = 0; i < allAccounts.count; i++) { } will crash

**Comment by farfromrefug** [comment]
PR https://github.com/EddyVerbruggen/nativescript-secure-storage/pull/43

**Comment by madmas** [comment]
as the PR was merged and a release forged, this issue can be closed, I think @EddyVerbruggen  ;)
