### ISSUE TITLE
Is it ready for Nativescript 7?

### ISSUE THREAD

**Issue by limux82** [EddyVerbruggen/nativescript-secure-storage#49]

**Comment by cjohn001** [comment]
Hello @EddyVerbruggen, same question from my side. From the package.json it seems like from 3.0 on it should be compatible. However, seems like it is not publish to NPM yet. Hence, would be great if you could report on the status here or publish the package. Thanks!

**Comment by EddyVerbruggen** [comment]
Yes, but I think the readme lacked an update. Please see the updated installation command: https://github.com/EddyVerbruggen/nativescript-secure-storage#nativescript-7-and-later
