### ISSUE TITLE
return without promise

### ISSUE THREAD

**Issue by chansc2016** [EddyVerbruggen/nativescript-secure-storage#9]
Hi, is there any option that I can use the get method without promise?
for example:

	var secureStorage = new SecureStorage();
	var fooValue= secureStorage.get({
		key: "foo"
	}).

and directly get fooValue.

**Comment by EddyVerbruggen** [comment]
Actually I was thinking of adding that to the plugin. So soon you will :)

**Comment by EddyVerbruggen** [comment]
Hi @chansc2016, please update to version 2.2.0 to use the new `sync` API - see the updated samples in the readme.

Enjoy!
